### ISSUE TITLE
Issues from RequestPolicy/requestpolicy

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#449]
<a href="https://github.com/myrdd"><img src="https://avatars.githubusercontent.com/u/4286829?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myrdd](https://github.com/myrdd)**
_Monday Aug 11, 2014 at 15:30 GMT_
_Originally opened as https://github.com/RequestPolicyContinuedTmp/requestpolicy/issues/1_

---

In this issue all issues from [RequestPolicy/requestpolicy](https://github.com/RequestPolicy/requestpolicy/issues) will be listed and organized.
This list is not complete, yet, although I have a list on my computer already. I will fill this post from time to time.
Of course, you're welcome to give hints, or in general contribute to this project!
# All issues (incomplete)

**general discussion about RP**
RequestPolicy#407
## bugs
- [x] ~~RequestPolicy#391~~
- [ ] _ip:port_ – RequestPolicy#394
- [ ] compatibility rules are hard-coded – RequestPolicy#403
- [ ] protocol compatibility rules
  - [ ] magnet links – RequestPolicy#410
  - [ ] Citrix GoToMeeting – RequestPolicy#412
  - [ ] `about:` pages
    - [ ] _about:healthreport_ – RequestPolicy#399
    - [ ] _about:accounts_ (firefox sync) – RequestPolicy#426
    - [ ] others (?)
- [ ] ajax – RequestPolicy#424
- [x] ~~flag stays gray – RequestPolicy#429, RequestPolicy#430~~
- [x] ~~flag in the new firefox menu – RequestPolicy#436~~
- [x] `wontfix` `crash` RequestPolicy#441
- [ ] RequestPolicy#443
## extension conflicts
- [x] RequestPolicy#291 – vertical toolbar
## issues affecting only version 0.5.x
- [ ] RequestPolicy#31
- [ ] RequestPolicy#198 – `bug?`
- [ ] RequestPolicy#214 – `bug`
- [ ] RequestPolicy#235
- [ ] RequestPolicy#261 – `bug`
- [ ] RequestPolicy#377 – `bug` _about:blank_
- [ ] RequestPolicy#379 – `bug`
- [ ] RequestPolicy#387 – `bug`
- [ ] RequestPolicy#420 – `bug` `can't reproduce`
- [ ] RequestPolicy#433 – `bug`
