### ISSUE TITLE
[task] unit tests for essential functionality

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#487]
In this first post I'll collect all unit tests that are possible or are planned. If you have ideas, please let me know. :)
- links
  - an url can be opened …
    - … in the same tab
    - … in a new tab
    - … in a new window
    - … in a new private window.
  - [x] clicking on HTML `<a>` Elements. see https://github.com/RequestPolicyContinued/requestpolicy/issues/480
  - [x] select a text link --> right-click --> open link.
- redirects
  - types of redirects
    - HTTP `Location` and `Refresh` headers
    - changing `document.location` in JavaScript.
    - `<meta http-equiv="refresh" …>` HTML elements
  - [ ] check that the redirect bar appears when blocking by default
    - [x] when opening a new page that redirects
    - [x] when clicking on a link that redirects
    - [ ] when opening a link in a new tab/window (redirect bar should appear in the correct tab)
    - [ ] when an embedded object (image, iframe, ...) is redirected
  - [ ] check if all buttons on the redirect bar work.

**_unsorted ideas:**_ (for some of the problems there might be already a mozmill test by mozilla)
- Backend
  - [ ] does the upgrade from 0.5.\* work (are the user policies imported?)
  - [ ] test whether "other origins" are recognized correctly.
  - [ ] check different schemes,
    - [ ] e.g. about:addons (https://github.com/RequestPolicyContinued/requestpolicy/issues/478)
  - [ ] check whether RequestPolicy starts up fast enough to catch all requests
  - [ ] check whether severe errors have appeared in the log – in any test.
  - [ ] check whether different types of requests are catched at all (using wireshark etc.?) – see also #586
- User interface
  - [ ] whether the settings pages work correctly
  - [ ] ensure that the setup tab is opened after install (https://github.com/RequestPolicyContinued/requestpolicy/issues/479)
  - [ ] whether the menu is populated correctly.
    - [ ] whether [no origin] is displayed correctly
- Browsing
  - [ ] link click and subsequent iframe to same link should not allow iframe.
  - [ ] history: back and forward
  - [ ] open the same url in several tabs/windows (https://github.com/RequestPolicyContinued/requestpolicy/issues/366 is possibly a bug)
- Website-specific
  - [ ] test sites with many links and other objects (see e.g. https://github.com/RequestPolicyContinued/requestpolicy/issues/369)
  - [ ] onerror "loops" – https://github.com/RequestPolicyContinued/requestpolicy/issues/441
- [ ] `about:addons` should work (installing addons)
- [ ] test loading of an erroneous json file

**_non-essential tests**_
- https://github.com/RequestPolicyContinued/requestpolicy/pull/506

**_unit test documentation:**_
https://github.com/RequestPolicyContinued/requestpolicy/wiki#unit-tests
