### ISSUE TITLE
upload RPC to AMO

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#543]
As RP 0.5.28 is marked as "Not available for Firefox  38  ~~36~~" on AMO (see #525) we should put RPC on AMO. This is a task list:

 - [x] Fix all known issues labeled [`dev-branch`](https://github.com/RequestPolicyContinued/requestpolicy/labels/dev-branch)
 - [x] Find and fix all *obvious* bugs regarding e10s & restartlessness (see #489)
 - [x] merge the the [`dev-restartless-and-e10s`](https://github.com/RequestPolicyContinued/requestpolicy/tree/dev-restartless-and-e10s) branch to `dev-1.0`
 - [x] create a new release (1.0.beta9) on github in order to find bugs I didn't discover yet
 - [x] #609 – change the [extension ID](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#id) – the result will be that ~~both RP and RPC~~ either RP or RPC can be installed
 - [x] rename the extension to *„RequestPolicy Continued“* (there was a discussion at https://github.com/RequestPolicyContinued/requestpolicy/issues/525#issuecomment-66656650) – it will be (again) renamed in the future, see #667.
 - [x] release a new version
 - [x] wait until [RPC 0.5.29](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/) gets approved, see https://github.com/RequestPolicyContinued/requestpolicy/issues/600#issuecomment-106958748
 - [ ] upload RPC 1.0 beta version to AMO.

After all that, we'll resume working on [compatibility issues](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+label%3Acompatibility) and [important bugs](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+label%3Abug+label%3Aimportant).

**Comment by myrdd** [comment]
I've added a new sub-task:

> create a new release (1.0.beta9) on github in order to find bugs I didn't discover yet

I'm planning to do that within a week.

**Comment by myrdd** [comment]
As version `1.0.beta9` is released now. The next version will have a new extension ID.

**Comment by myrdd** [comment]
Sadly I could not finish this task until now, and I still need several weeks because I don't have much time these days.

What does this mean? On tuesday, Firefox 38 will be released as *stable*, and anyone visiting the [RequestPolicy's AMO page](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy/) using Fx38 or greater will see this gray button:

![button "add to firefox" on AMO is greyed out](https://cloud.githubusercontent.com/assets/4286829/7555824/2be590d2-f758-11e4-9f1d-e0a1dd0a558d.jpg)

However, it should still be possible to install it anyway:

!["Install Anyway" button](https://cloud.githubusercontent.com/assets/4286829/7555831/6f411c0c-f758-11e4-99ee-cc27802a57e4.jpg)

---------------------------

I think that's ok, but what I hope is that there won't be too many people installing *RPContinued* and then being frustrated because RPC is still beta.

I've taken some time to think about this­, and I would say: let's see what happens. If it turns out that we dislike this „incompatibility“, we could still ask the AMO team to push the incompatibility to a later version of firefox. Any opinion about that?

**Comment by Isgar** [comment]
I just want to point that this issue needs to be done when Firefox 40 is released, as they require addons to be signed.

**Comment by myrdd** [comment]
Thanks Isgar, it has already been reported. #600.

I've written a detailed plan about extension signing. https://github.com/RequestPolicyContinued/requestpolicy/issues/600#issuecomment-106958748.

**Comment by myrdd** [comment]
current Queue Position: 158 of 240

**Comment by myrdd** [comment]
Good news, RPC 0.5 recently got approved: https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/

I guess I'll upload 1.0beta on AMO as soon as the incompatibilities are fixed, especially #354.

**Comment by myrdd** [comment]
I won't upload 1.0 to AMO; it would conflict with the 0.5 version. Of course, as soon as 1.0 replaces 0.5, 1.0 will be available on AMO.

**Comment by myrdd** [comment]
FYI:

I've changed my mind. The RPC 1.0beta is now available as a _separate_ add-on on AMO:
https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/

The Legacy version (0.5) is available as well:
https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-legacy/
