### ISSUE TITLE
WE transition: switch locale (i18n) system

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#873]
The WE i18n system is described here:

- Guide: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization
- API docs: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n

The main function we need is `browser.i18n.getMessage()` [[MDN docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/getMessage)]:
```js
browser.i18n.getMessage(
  messageName,  // string
  substitutions // optional any
)
```
It will replace [`StringUtils.$str()`](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/lib/utils/strings.js).

BTW, we do **not** need [Locale-dependent CSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Locale-dependent_CSS)

---

Since we are going to maintain a XPCOM version of RPC (e.g. for palemoon) we need a `browser.i18n.getMessage()` fake API. We can take the code from Mozilla (licensed as MPL 2.0, so the copy-pasted code needs to be in a separate file with MPL2.0 header).

**I've tracked down the `browser.i18n.getMessage()` system:**

**[`browser.i18n.getMessage()`](https://dxr.mozilla.org/mozilla-central/rev/b2200418de0bf215a84d84317d247363536369dd/toolkit/components/extensions/ext-i18n.js#12-14)**

```js
getMessage: function(messageName, substitutions) {
  return extension.localizeMessage(messageName, substitutions, {cloneScope: context.cloneScope});
},
```

**[`ExtensionData.localizeMessage()`](https://dxr.mozilla.org/mozilla-central/rev/b2200418de0bf215a84d84317d247363536369dd/toolkit/components/extensions/Extension.jsm#668-670)**

```js
localizeMessage(...args) {
  return this.localeData.localizeMessage(...args);
}
```

**[`ExtensionData.localeData`](https://dxr.mozilla.org/mozilla-central/rev/b2200418de0bf215a84d84317d247363536369dd/toolkit/components/extensions/Extension.jsm#728-732)**

```js
this.localeData = new LocaleData({
  defaultLocale: this.defaultLocale,
  locales,
  builtinMessages: this.builtinMessages,
});
```

**[`LocaleData.localizeMessage()`](https://dxr.mozilla.org/mozilla-central/rev/b2200418de0bf215a84d84317d247363536369dd/toolkit/components/extensions/ExtensionCommon.jsm#1357-1428)**

```js
localizeMessage(message, substitutions = [], options = {}) {
  // ...
},
```

---

**Tasks**

- [x] issue #876: convert `*.properties` to `message.json` files
- [x] move RPC description localization from [`install.rdf`](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/conditional/legacy/install.rdf) to the WE i18n json files
  - **details:** in `install.rdf`, replace all `<em:localized>` lines by *one single line* containing `<!-- @echo INSTALL_RDF_I18N -->`
- [x] extend the `gulpfile.js` to create the `INSTALL_RDF_I18N` string for `install.rdf` by parsing the i18n json files.
  - **details:** put the `INSTALL_RDF_I18N` creation script in the [`preprocessContext` gulp task](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/gulpfile.js#L313-L324)
- [ ] implement a fake `browser.i18n.getMessage()` function
  - **details:** see above. don't forget the MPL2 license header
- [ ] replace all usages of `StringUtils.$str()` by `browser.i18n.getMessage()`
- [ ] check if everything works ;)
- [ ] remove all  `*.properties` files

**Comment by myrdd** [comment]
Regarding the current localization of the settings pages (XUL / HTML), see this piece of code:
https://github.com/RequestPolicyContinued/requestpolicy/blob/5697d0e2d7d8aa56c86fc21bda5cc306e96bc5af/src/content/lib/utils/xul.js#L136-L160

Strings like `"&foobar;"` are replaced by the string returned by `StringUtils.$str("foobar")`.

**Comment by jrrdev** [comment]
I can take care of it because I will need it very soon for issue #871

**Comment by myrdd** [comment]
I've created subtask issue #876: convert `*.properties` to `message.json` files

@jrrdev do you think you could take it?

**Comment by myrdd** [comment]
The first three tasks are done :)

@jrrdev do you have some time to implement `browser.i18n.getMessage()`, and to change the add-on's code to use that API function?

Please note that we can take `browser.i18n.getMessage()` fake API code from Mozilla, see the issue's comment / the first comment.
(If it helps, you can also use this function: https://github.com/myrdd/requestpolicy/blob/17ff5d586b9974fe2c14999ace2e47169bd5edde/gulpfile.js#L225-L235)

**Comment by jrrdev** [comment]
Hi,
I started to look at Mozilla's code but I didn't have much time last week to look deeper.
Fortunately, I have a lot of free time this week :-) I hope to finish the remaining task by the end of the week

**Comment by myrdd** [comment]
Great! :)

**Comment by jrrdev** [comment]
@myrdd I have some trouble to implement [ExtensionData.readDirectory](https://github.com/mozilla/gecko/blob/c71e0bc841d2cc7c56cb4bf4b68780b7308f7eba/toolkit/components/extensions/Extension.jsm#L374-L427) because I need to fetch the directory contents from `chrome://rpcontinued/content/_locales` (thus it can't create a nsIFileURL because of scheme `chrome://`).
I found a workaround using xhr and parsing the http response which looks like (I made a test on /content/bootstrap):
```
300: jar:file:///tmp/tmpC5HhWt.mozrunner/extensions/rpcontinued@non-amo.requestpolicy.org.xpi!/content/bootstrap/
200: filename content-length last-modified file-type
201: bootstrap.jsm 8674 Sun,%2017%20Dec%202017%2020:28:40%20GMT FILE
201: data/ 0 Sat,%2002%20Dec%202017%2019:01:14%20GMT DIRECTORY
201: environments/ 0 Sat,%2002%20Dec%202017%2019:01:14%20GMT DIRECTORY
201: modules/ 0 Sat,%2002%20Dec%202017%2019:01:14%20GMT DIRECTORY
```

But it seems a little hackish... Do you have some ideas on a better way to proceed with ?

**Comment by myrdd** [comment]
@jrrdev IMHO you could simply hard-code the list of locales, just like it is done for `install.rdf`. I've added commit https://github.com/myrdd/requestpolicy/commit/98458930858402297f09eba38966ada88311928f onto https://github.com/myrdd/requestpolicy/tree/feature/we-i18n. Now you can simply use `bootstrap/data/locales`. :)

**Comment by jrrdev** [comment]
It is indeed much easier to deal with the hard-coded list :smile: Thank you !

**Comment by cheggerdev** [comment]
I think this issue can be closed, no?

**Comment by myrdd** [comment]
true, thanks
