### ISSUE TITLE
[WebExtension port] data migration, import/export, v0 rules

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#892]
### task list

* [x] "classes/old-rules.ts" and "controllers/old-rules-controller.ts" **done**
    * [x] `rp.services.rules.v0` = service for importing v0 rules
      * [x] `DomainUtil` (which is a dependency) -> `rp.services.uri`
    * [x] `rp.migration.v0Rules` [xpcom build only] = module for automatic import of v0 rule strings from about:config"
* [x] automatic migration **done**
    * will be `rp.migration.xpcomToWE`
    * _how it works_
        * the xpcom build has an _embedded Web Extension_, I call it _eWE_
        * the addon first waits for the v0 rules migration (`rp.migration.v0Rules`) to finish. Then the addon sends all settings and rules to the eWE, which stores them into the WE storage
    * [x] implement `weApi.storage` (part of #893) **done**
    * [x] implement `rp.migration.xpcomToWE` **done**
    * [x] write tests
        * [x] settings and and rules are migrated on startup **working**
        * [x] some more tests **working**
        * [x] changed settings/rules are propagated immediately to the eWE **working**
    * [x] perform manual tests
        * [x] settings and and rules are migrated on startup **working**
        * [x] changed settings/rules are propagated immediately to the eWE **working**
        * [x] changed settings/rules _in the eWE_ are propagated to the legacy component _on startup_ (by setting `"lastStorageChange"` to, e.g., `2018-06-20T16:11:02.748Z`) **working**
    * [x] ~~remember (in a pref) whether migration has been successful~~
        * ~~as soon as RP is released as a WE, show a notification which includes the success message~~
        * ~~the user needs to be informed if migration was unsuccessful~~
* [ ] manual import/export (see also #342)
    * this is necessary as a ”back-up“ way to migrate rules if the automatic rule has been failing
    * [x] v0 functions (`rp.services.rules.v0`) **done**
    * [x] v1 functions **done**
    * [ ] provide functions in the settings
    * [ ] provide functions on the "setup" page

**Comment by myrdd** [comment]
The module `rp.services.rules.v0` still depends on these xpcom services/objects

* nsIIDNService
* nsIURI
* nsIEffectiveTLDService

(The migration of all these services/objects is covered in #894.) Since automatic storage migration is the most urgent issue right now, #894 will be kept back for now.

**Comment by myrdd** [comment]
`rp.services.rules.v0` and `rp.migration.v0Rules` are done

**Comment by myrdd** [comment]
automatic migration is done in the (big) commit 09766639095606218304456aa83ac7377461ff93.
it's available as dev release [1.0.beta13.2.2448.r2f5182f6d.pre](https://github.com/RequestPolicyContinued/requestpolicy/issues/754#issuecomment-416034139).

manual import/export (see first post) is now tracked in #342.
