### ISSUE TITLE
 [WebExtension port] data storage, privacy settings

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#893]
### task list

* [x] pref branch -> `weApi.storage` **done**
* [ ] files (i.e., subscription files) -> `weApi.storage` **WIP**
* [ ] privacy settings -> `privacy.network`

**Comment by myrdd** [comment]
#892 requires `get()` and `onChanged`. The latter seems to fail currently, so some tests need to be written.

**Comment by myrdd** [comment]
Most tasks are done. I'm going to create a new nightly release.
