### ISSUE TITLE
 [WebExtension port] URI class, DomainUtils, PSL

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#894]
### task list

* [ ] nsIEffectiveTLDService &rarr; node package `psl` **WIP**
* [ ] URL preparations
  * [ ] No longer differentiate between `"host === null"` and `"host === undefined"`.
    * Three possibilities:
      * `"normal-host.com"`
      * `""` (empty host, e.g. `"file:///"`)
      * `null`/`undefined` (e.g. `"about:config"`)
  * [ ] "Request": take a string, not a nsIUri object
  * …
* [ ] URLs
  * [ ] get replacement for nsIURI **WIP**
  * [ ] nsIURI &rarr; Uri class
  * [ ] nsIIDNService.convertToDisplayIDN()
  * …
* …
